server:
  port: 8082
  servlet:
    contextPath: /eshop
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: eshop

spring:
  datasource:
    username: toto
    password: toto
    url: jdbc:postgresql://localhost:5432/eshop
    driverClassName: org.postgresql.Driver